/**
 * A minimal QR Code encoder, byte mode, error-correction level M.
 *
 * WHY THIS EXISTS: the component kit ships no QR renderer and this project has no
 * QR dependency (see package.json). `POST /api/user/2fa/setup` answers with an
 * `otpauth://` URI that the user has to get into an authenticator app, and a QR
 * code is the only practical transport. Rather than add a dependency to a
 * package.json several agents are editing at once, the encoder lives here.
 *
 * SCOPE, deliberately narrow:
 *   - Byte mode only. An `otpauth://` URI is mixed-case with punctuation, so
 *     alphanumeric mode never applies and the segment optimiser is dead weight.
 *   - Error-correction level M only (15% recovery), which is what authenticator
 *     QR codes conventionally use.
 *   - Versions 1 to 40, chosen automatically as the smallest that fits.
 *
 * The algorithm is the one in ISO/IEC 18004. Correctness is pinned by
 * `__tests__/qr-encode.test.ts`, which compares whole module matrices against
 * fixtures generated by the `segno` reference encoder.
 */

/** Error-correction codewords per block, level M, indexed by version (1-40). */
const EC_CODEWORDS_PER_BLOCK_M = [
  10, 16, 26, 18, 24, 16, 18, 22, 22, 26,
  30, 22, 22, 24, 24, 28, 28, 26, 26, 26,
  26, 28, 28, 28, 28, 28, 28, 28, 28, 28,
  28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
] as const

/** Number of error-correction blocks, level M, indexed by version (1-40). */
const EC_BLOCKS_M = [
  1, 1, 1, 2, 2, 4, 4, 4, 5, 5,
  5, 8, 9, 9, 10, 10, 11, 13, 14, 16,
  17, 17, 18, 20, 21, 23, 25, 26, 28, 29,
  31, 33, 35, 37, 38, 40, 43, 45, 47, 49,
] as const

/** The three mask-penalty weights and the balance weight from the specification. */
const PENALTY_RUN = 3
const PENALTY_BOX = 3
const PENALTY_FINDER_LIKE = 40
const PENALTY_BALANCE = 10

const MIN_VERSION = 1
const MAX_VERSION = 40

/** Level M's two-bit format value, used when computing the format information. */
const FORMAT_BITS_M = 0

export type QrMatrix = {
  /** Side length in modules, `4 * version + 17`. */
  size: number
  /** Row-major, `true` meaning a dark module. */
  modules: readonly (readonly boolean[])[]
  version: number
  /** The data mask (0-7) the encoder selected, or the one that was forced. */
  mask: number
}

export class QrEncodeError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'QrEncodeError'
  }
}

function bit(value: number, index: number): boolean {
  return ((value >>> index) & 1) !== 0
}

/**
 * Total module count available to data and error correction, before subtracting
 * the function patterns' codewords. Straight out of the specification's Annex.
 */
function rawDataModules(version: number): number {
  let result = (16 * version + 128) * version + 64
  if (version >= 2) {
    const alignmentCount = Math.floor(version / 7) + 2
    result -= (25 * alignmentCount - 10) * alignmentCount - 55
    if (version >= 7) result -= 36
  }
  return result
}

function totalCodewords(version: number): number {
  return Math.floor(rawDataModules(version) / 8)
}

/** Codewords left for payload once the error-correction codewords are reserved. */
export function dataCodewordCount(version: number): number {
  return (
    totalCodewords(version)
    - EC_CODEWORDS_PER_BLOCK_M[version - 1] * EC_BLOCKS_M[version - 1]
  )
}

/** Byte-mode character-count field width: 8 bits up to version 9, 16 above. */
function characterCountBits(version: number): number {
  return version <= 9 ? 8 : 16
}

/** Largest byte-mode payload, in bytes, that fits a version at level M. */
export function byteCapacity(version: number): number {
  const availableBits = dataCodewordCount(version) * 8 - 4 - characterCountBits(version)
  return Math.floor(availableBits / 8)
}

function chooseVersion(byteLength: number): number {
  for (let version = MIN_VERSION; version <= MAX_VERSION; version += 1) {
    if (byteLength <= byteCapacity(version)) return version
  }
  throw new QrEncodeError(`Content is too long to encode as a QR code (${byteLength} bytes)`)
}

// ---------------------------------------------------------------------------
// GF(256) arithmetic for Reed-Solomon, primitive polynomial 0x11D.
// ---------------------------------------------------------------------------

function gfMultiply(left: number, right: number): number {
  let product = 0
  for (let index = 7; index >= 0; index -= 1) {
    product = (product << 1) ^ ((product >>> 7) * 0x11d)
    product ^= ((right >>> index) & 1) * left
  }
  return product & 0xff
}

/** Coefficients of the generator polynomial of the given degree, highest term omitted. */
function reedSolomonDivisor(degree: number): number[] {
  const divisor = new Array<number>(degree).fill(0)
  divisor[degree - 1] = 1

  let root = 1
  for (let step = 0; step < degree; step += 1) {
    for (let index = 0; index < degree; index += 1) {
      divisor[index] = gfMultiply(divisor[index], root)
      if (index + 1 < degree) divisor[index] ^= divisor[index + 1]
    }
    root = gfMultiply(root, 0x02)
  }
  return divisor
}

function reedSolomonRemainder(data: readonly number[], divisor: readonly number[]): number[] {
  const remainder = new Array<number>(divisor.length).fill(0)
  for (const byte of data) {
    const factor = byte ^ (remainder.shift() ?? 0)
    remainder.push(0)
    for (let index = 0; index < divisor.length; index += 1) {
      remainder[index] ^= gfMultiply(divisor[index], factor)
    }
  }
  return remainder
}

// ---------------------------------------------------------------------------
// Payload assembly
// ---------------------------------------------------------------------------

function toUtf8Bytes(text: string): number[] {
  if (typeof TextEncoder !== 'undefined') return Array.from(new TextEncoder().encode(text))

  // Fallback for environments without TextEncoder; encodeURIComponent is UTF-8.
  const escaped = encodeURIComponent(text)
  const bytes: number[] = []
  for (let index = 0; index < escaped.length; index += 1) {
    if (escaped[index] === '%') {
      bytes.push(Number.parseInt(escaped.slice(index + 1, index + 3), 16))
      index += 2
    } else {
      bytes.push(escaped.charCodeAt(index))
    }
  }
  return bytes
}

/** Mode indicator, character count, payload, terminator and the 0xEC/0x11 pad. */
function buildDataCodewords(bytes: readonly number[], version: number): number[] {
  const bits: boolean[] = []
  const appendBits = (value: number, width: number) => {
    for (let index = width - 1; index >= 0; index -= 1) bits.push(bit(value, index))
  }

  appendBits(0b0100, 4)
  appendBits(bytes.length, characterCountBits(version))
  for (const byte of bytes) appendBits(byte, 8)

  const capacityBits = dataCodewordCount(version) * 8
  const terminator = Math.min(4, capacityBits - bits.length)
  for (let index = 0; index < terminator; index += 1) bits.push(false)
  while (bits.length % 8 !== 0) bits.push(false)

  const codewords: number[] = []
  for (let index = 0; index < bits.length; index += 8) {
    let byte = 0
    for (let offset = 0; offset < 8; offset += 1) byte = (byte << 1) | (bits[index + offset] ? 1 : 0)
    codewords.push(byte)
  }

  const padBytes = [0xec, 0x11]
  let padIndex = 0
  while (codewords.length < dataCodewordCount(version)) {
    codewords.push(padBytes[padIndex % 2])
    padIndex += 1
  }
  return codewords
}

/** Splits into blocks, appends each block's ECC, then interleaves both. */
function addErrorCorrectionAndInterleave(data: readonly number[], version: number): number[] {
  const blockCount = EC_BLOCKS_M[version - 1]
  const eccPerBlock = EC_CODEWORDS_PER_BLOCK_M[version - 1]
  const rawCodewords = totalCodewords(version)
  const shortBlockCount = blockCount - (rawCodewords % blockCount)
  const shortBlockLength = Math.floor(rawCodewords / blockCount)

  const divisor = reedSolomonDivisor(eccPerBlock)
  const blocks: number[][] = []
  let cursor = 0
  for (let index = 0; index < blockCount; index += 1) {
    const length = shortBlockLength - eccPerBlock + (index < shortBlockCount ? 0 : 1)
    const block = data.slice(cursor, cursor + length)
    cursor += length
    const ecc = reedSolomonRemainder(block, divisor)
    // The short blocks carry a placeholder so every block has the same array
    // length; the interleaver skips that slot rather than emitting it.
    if (index < shortBlockCount) block.push(0)
    blocks.push(block.concat(ecc))
  }

  const interleaved: number[] = []
  for (let index = 0; index < blocks[0].length; index += 1) {
    for (let blockIndex = 0; blockIndex < blocks.length; blockIndex += 1) {
      if (index === shortBlockLength - eccPerBlock && blockIndex < shortBlockCount) continue
      interleaved.push(blocks[blockIndex][index])
    }
  }
  return interleaved
}

// ---------------------------------------------------------------------------
// Symbol layout
// ---------------------------------------------------------------------------

type Canvas = {
  size: number
  modules: boolean[][]
  reserved: boolean[][]
  version: number
}

function createCanvas(version: number): Canvas {
  const size = version * 4 + 17
  return {
    size,
    version,
    modules: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
    reserved: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
  }
}

function setFunctionModule(canvas: Canvas, x: number, y: number, dark: boolean): void {
  canvas.modules[y][x] = dark
  canvas.reserved[y][x] = true
}

function alignmentPatternPositions(version: number): number[] {
  if (version === 1) return []

  const count = Math.floor(version / 7) + 2
  const step = version === 32 ? 26 : Math.ceil((version * 4 + 4) / (count * 2 - 2)) * 2
  const positions = [6]
  for (let position = version * 4 + 10; positions.length < count; position -= step) {
    positions.splice(1, 0, position)
  }
  return positions
}

function drawFinderPattern(canvas: Canvas, centerX: number, centerY: number): void {
  for (let dy = -4; dy <= 4; dy += 1) {
    for (let dx = -4; dx <= 4; dx += 1) {
      const x = centerX + dx
      const y = centerY + dy
      if (x < 0 || x >= canvas.size || y < 0 || y >= canvas.size) continue
      const distance = Math.max(Math.abs(dx), Math.abs(dy))
      setFunctionModule(canvas, x, y, distance !== 2 && distance !== 4)
    }
  }
}

function drawAlignmentPattern(canvas: Canvas, centerX: number, centerY: number): void {
  for (let dy = -2; dy <= 2; dy += 1) {
    for (let dx = -2; dx <= 2; dx += 1) {
      setFunctionModule(
        canvas,
        centerX + dx,
        centerY + dy,
        Math.max(Math.abs(dx), Math.abs(dy)) !== 1,
      )
    }
  }
}

function drawFormatBits(canvas: Canvas, mask: number): void {
  const value = (FORMAT_BITS_M << 3) | mask
  let remainder = value
  for (let index = 0; index < 10; index += 1) {
    remainder = (remainder << 1) ^ ((remainder >>> 9) * 0x537)
  }
  const bits = (((value << 10) | remainder) ^ 0x5412) & 0x7fff

  for (let index = 0; index <= 5; index += 1) setFunctionModule(canvas, 8, index, bit(bits, index))
  setFunctionModule(canvas, 8, 7, bit(bits, 6))
  setFunctionModule(canvas, 8, 8, bit(bits, 7))
  setFunctionModule(canvas, 7, 8, bit(bits, 8))
  for (let index = 9; index < 15; index += 1) {
    setFunctionModule(canvas, 14 - index, 8, bit(bits, index))
  }

  for (let index = 0; index < 8; index += 1) {
    setFunctionModule(canvas, canvas.size - 1 - index, 8, bit(bits, index))
  }
  for (let index = 8; index < 15; index += 1) {
    setFunctionModule(canvas, 8, canvas.size - 15 + index, bit(bits, index))
  }
  setFunctionModule(canvas, 8, canvas.size - 8, true)
}

function drawVersionBits(canvas: Canvas): void {
  if (canvas.version < 7) return

  let remainder = canvas.version
  for (let index = 0; index < 12; index += 1) {
    remainder = (remainder << 1) ^ ((remainder >>> 11) * 0x1f25)
  }
  const bits = (canvas.version << 12) | remainder

  for (let index = 0; index < 18; index += 1) {
    const dark = bit(bits, index)
    const far = canvas.size - 11 + (index % 3)
    const near = Math.floor(index / 3)
    setFunctionModule(canvas, far, near, dark)
    setFunctionModule(canvas, near, far, dark)
  }
}

function drawFunctionPatterns(canvas: Canvas): void {
  for (let index = 0; index < canvas.size; index += 1) {
    setFunctionModule(canvas, 6, index, index % 2 === 0)
    setFunctionModule(canvas, index, 6, index % 2 === 0)
  }

  drawFinderPattern(canvas, 3, 3)
  drawFinderPattern(canvas, canvas.size - 4, 3)
  drawFinderPattern(canvas, 3, canvas.size - 4)

  const positions = alignmentPatternPositions(canvas.version)
  const last = positions.length - 1
  for (let row = 0; row <= last; row += 1) {
    for (let column = 0; column <= last; column += 1) {
      const isFinderCorner = (row === 0 && column === 0)
        || (row === 0 && column === last)
        || (row === last && column === 0)
      if (isFinderCorner) continue
      drawAlignmentPattern(canvas, positions[column], positions[row])
    }
  }

  // Reserves the format and version areas; the real format bits are written
  // again once a mask has been chosen.
  drawFormatBits(canvas, 0)
  drawVersionBits(canvas)
}

function drawCodewords(canvas: Canvas, codewords: readonly number[]): void {
  let bitIndex = 0
  let right = canvas.size - 1

  while (right >= 1) {
    // Column 6 is the vertical timing pattern. The walk skips it by snapping the
    // pair one column left, and every later pair is measured from there — hence
    // the reassignment rather than a local alias.
    if (right === 6) right = 5

    for (let vertical = 0; vertical < canvas.size; vertical += 1) {
      for (let offset = 0; offset < 2; offset += 1) {
        const x = right - offset
        const upward = ((right + 1) & 2) === 0
        const y = upward ? canvas.size - 1 - vertical : vertical
        if (canvas.reserved[y][x] || bitIndex >= codewords.length * 8) continue
        canvas.modules[y][x] = bit(codewords[bitIndex >>> 3], 7 - (bitIndex & 7))
        bitIndex += 1
      }
    }

    right -= 2
  }
}

function maskApplies(mask: number, x: number, y: number): boolean {
  switch (mask) {
    case 0: return (x + y) % 2 === 0
    case 1: return y % 2 === 0
    case 2: return x % 3 === 0
    case 3: return (x + y) % 3 === 0
    case 4: return (Math.floor(x / 3) + Math.floor(y / 2)) % 2 === 0
    case 5: return ((x * y) % 2) + ((x * y) % 3) === 0
    case 6: return (((x * y) % 2) + ((x * y) % 3)) % 2 === 0
    default: return (((x + y) % 2) + ((x * y) % 3)) % 2 === 0
  }
}

function applyMask(canvas: Canvas, mask: number): void {
  for (let y = 0; y < canvas.size; y += 1) {
    for (let x = 0; x < canvas.size; x += 1) {
      if (canvas.reserved[y][x]) continue
      if (maskApplies(mask, x, y)) canvas.modules[y][x] = !canvas.modules[y][x]
    }
  }
}

/** Counts 1:1:3:1:1 finder-like sequences in a run-length history window. */
function countFinderLike(history: readonly number[]): number {
  const unit = history[1]
  const core = unit > 0
    && history[2] === unit
    && history[3] === unit * 3
    && history[4] === unit
    && history[5] === unit
  const leading = core && history[0] >= unit * 4 && history[6] >= unit ? 1 : 0
  const trailing = core && history[6] >= unit * 4 && history[0] >= unit ? 1 : 0
  return leading + trailing
}

function pushRun(history: number[], length: number, size: number): void {
  // A run that starts at the edge is preceded by the quiet zone, which counts
  // as light modules for the finder-like test.
  const adjusted = history[0] === 0 ? length + size : length
  history.pop()
  history.unshift(adjusted)
}

function scanLinePenalty(
  read: (index: number) => boolean,
  size: number,
): { runs: number; finderLike: number } {
  let runs = 0
  let finderLike = 0
  let runColor = false
  let runLength = 0
  const history = [0, 0, 0, 0, 0, 0, 0]

  for (let index = 0; index < size; index += 1) {
    if (read(index) === runColor) {
      runLength += 1
      if (runLength === 5) runs += PENALTY_RUN
      else if (runLength > 5) runs += 1
      continue
    }
    pushRun(history, runLength, size)
    if (!runColor) finderLike += countFinderLike(history) * PENALTY_FINDER_LIKE
    runColor = read(index)
    runLength = 1
  }

  if (runColor) {
    pushRun(history, runLength, size)
    runLength = 0
  }
  pushRun(history, runLength + size, size)
  finderLike += countFinderLike(history) * PENALTY_FINDER_LIKE

  return { runs, finderLike }
}

function penaltyScore(canvas: Canvas): number {
  const { size, modules } = canvas
  let score = 0

  for (let y = 0; y < size; y += 1) {
    const line = scanLinePenalty((x) => modules[y][x], size)
    score += line.runs + line.finderLike
  }
  for (let x = 0; x < size; x += 1) {
    const line = scanLinePenalty((y) => modules[y][x], size)
    score += line.runs + line.finderLike
  }

  for (let y = 0; y < size - 1; y += 1) {
    for (let x = 0; x < size - 1; x += 1) {
      const color = modules[y][x]
      if (
        color === modules[y][x + 1]
        && color === modules[y + 1][x]
        && color === modules[y + 1][x + 1]
      ) {
        score += PENALTY_BOX
      }
    }
  }

  let dark = 0
  for (const row of modules) {
    for (const module of row) if (module) dark += 1
  }
  const total = size * size
  score += (Math.ceil(Math.abs(dark * 20 - total * 10) / total) - 1) * PENALTY_BALANCE

  return score
}

/**
 * Encodes `text` as a QR Code matrix at error-correction level M.
 *
 * @param forcedMask - Pins the data mask instead of selecting the lowest-penalty
 *   one. Only the tests use it, to compare against reference fixtures per mask.
 * @throws {QrEncodeError} when the content exceeds version 40's byte capacity.
 */
export function encodeQr(text: string, forcedMask?: number): QrMatrix {
  const bytes = toUtf8Bytes(text)
  const version = chooseVersion(bytes.length)
  const codewords = addErrorCorrectionAndInterleave(buildDataCodewords(bytes, version), version)

  let best: { canvas: Canvas; mask: number } | null = null
  const candidates = forcedMask === undefined ? [0, 1, 2, 3, 4, 5, 6, 7] : [forcedMask]
  let bestScore = Number.POSITIVE_INFINITY

  for (const mask of candidates) {
    const canvas = createCanvas(version)
    drawFunctionPatterns(canvas)
    drawCodewords(canvas, codewords)
    applyMask(canvas, mask)
    drawFormatBits(canvas, mask)

    const score = penaltyScore(canvas)
    if (score < bestScore) {
      bestScore = score
      best = { canvas, mask }
    }
  }

  if (!best) throw new QrEncodeError('No QR code mask could be selected')

  return {
    size: best.canvas.size,
    modules: best.canvas.modules,
    version,
    mask: best.mask,
  }
}
